import "./globals.css";
import type { Metadata } from "next";
import { Toaster } from "sonner";
import { Providers } from "@/providers/providers";
import { ModalsProvider } from "@/providers/modals-provider";

export const metadata: Metadata = {
  title: "Hono | nextjs",
  description: "Generated by hono",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Toaster />
        <Providers>
          <ModalsProvider />
          {children}
        </Providers>
      </body>
    </html>
  );
}
